### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-susantomo#2]
- [x] input tomo mrc stack has to be float32
- [x] scipion coord/alignment -> tbl
- [x] basic viewer
- [x] protocol to make subsets by CC or ref num
- [x] continue mode
- [ ] add export coords protocol (update positions with shifts)
- [x] add params to MRA: denoise, 2d refinement
- [ ] save ptcl alignment info: susan ptclsraw -> scipion
- [ ] replace matrix2eulerAngles (see https://github.com/scipion-em/scipion-em-continuousflex/issues/148)

**Comment by MohamadHarastani** [comment]
Hi @azazellochg 
By chance I saw you linked the issue with matrix2eulerAngles. Give a try this solution:
```
from scipy.spatial.transform import Rotation
rot, tilt, psi = Rotation.from_matrix(T).inv().as_euler('ZYZ', degrees=True)
```
Cheers
